"""new fields in user model

Revision ID: 0fe8918da1d2
Revises: b46fb06df473
Create Date: 2022-03-12 23:35:55.218619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fe8918da1d2'
down_revision = 'b46fb06df473'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('family', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('mobile', sa.String(length=16), nullable=True))
    op.add_column('user', sa.Column('website', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_mobile'), 'user', ['mobile'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_mobile'), table_name='user')
    op.drop_column('user', 'website')
    op.drop_column('user', 'mobile')
    op.drop_column('user', 'family')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
